package se.sundsvall.processengine.parkingpermit.integration.casedata.enums;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(example = "PARKING_PERMIT")
public enum CaseType {

    // BYGGR
    NYBYGGNAD_ANSOKAN_OM_BYGGLOV,
    ANMALAN_ATTEFALL,
    // ECOS
    REGISTRERING_AV_LIVSMEDEL,
    ANMALAN_INSTALLATION_VARMEPUMP,
    ANSOKAN_TILLSTAND_VARMEPUMP,
    ANSOKAN_OM_TILLSTAND_ENSKILT_AVLOPP,
    ANMALAN_INSTALLTION_ENSKILT_AVLOPP_UTAN_WC,
    ANMALAN_ANDRING_AVLOPPSANLAGGNING,
    ANMALAN_ANDRING_AVLOPPSANORDNING,
    ANMALAN_HALSOSKYDDSVERKSAMHET,

    PARKING_PERMIT,
    LOST_PARKING_PERMIT

}
